---
endpoints:
  -
    component: JsonRestStatSet
    name: forest.all.status
    url: /manage/v2/forests?view=status&format=json
  -
    component: JsonRestStatSet
    name: host.all.status
    url: /manage/v2/hosts?view=status&format=json
  -
    component: JsonRestStatSet
    name: server.all.status
    url: /manage/v2/servers?view=status&format=json